version: '3'

services:
    api-postgrest:
        image: postgrest/postgrest
        ports:
            - 3000:3000
        depends_on:
            - database-postgres
        environment:
            - PGRST_DB_URI=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database-postgres:5433/${DATABASE_NAME}
            - PGRST_DB_SCHEMA=${PGRST_DB_SCHEMA} #public
            - PGRST_DB_ANON_ROLE=${PGRST_DB_ANON_ROLE} #web_anon

    database-postgres:
        image: postgres:14
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=${DATABASE_USER} #postgres
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD} #postgres
            - POSTGRES_DB=${DATABASE_NAME} #postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: